In [1]:
!pip -q install requests beautifulsoup4 pandas

In [8]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import sqlite3
import time
from pathlib import Path
from IPython.display import display

BASE_URL = "https://books.toscrape.com/"
GBP_TO_INR = 105.50

print("Fixed conversion rate: 1 GBP =", GBP_TO_INR, "INR")

Fixed conversion rate: 1 GBP = 105.5 INR

In [9]:
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Data Pipeline Student Project)"
}

def get_soup(url):
    response = requests.get(url, headers=HEADERS, timeout=20)
    response.raise_for_status()
    return BeautifulSoup(response.text, "html.parser")


def rating_to_int(rating_text):
    mapping = {
        "One": 1,
        "Two": 2,
        "Three": 3,
        "Four": 4,
        "Five": 5
    }
    return mapping[rating_text.strip()]

import re
def clean_price(price_text):
    # Use a regular expression to find all numbers and the decimal point
    # and join them to form a clean numerical string
    clean_str = re.sub(r'[^.0-9]', '', price_text)
    return float(clean_str)

In [10]:
soup = get_soup(BASE_URL)

categories = []

for link in soup.select("div.side_categories ul li ul li a"):
    category_name = link.get_text(strip=True)
    category_url = requests.compat.urljoin(
        BASE_URL,
        link["href"]
    )

    categories.append(
        (category_name, category_url)
    )

print("Total categories found:", len(categories))

for category in categories[:10]:
    print(category)

Total categories found: 50
('Travel', 'https://books.toscrape.com/catalogue/category/books/travel_2/index.html')
('Mystery', 'https://books.toscrape.com/catalogue/category/books/mystery_3/index.html')
('Historical Fiction', 'https://books.toscrape.com/catalogue/category/books/historical-fiction_4/index.html')
('Sequential Art', 'https://books.toscrape.com/catalogue/category/books/sequential-art_5/index.html')
('Classics', 'https://books.toscrape.com/catalogue/category/books/classics_6/index.html')
('Philosophy', 'https://books.toscrape.com/catalogue/category/books/philosophy_7/index.html')
('Romance', 'https://books.toscrape.com/catalogue/category/books/romance_8/index.html')
('Womens Fiction', 'https://books.toscrape.com/catalogue/category/books/womens-fiction_9/index.html')
('Fiction', 'https://books.toscrape.com/catalogue/category/books/fiction_10/index.html')
('Childrens', 'https://books.toscrape.com/catalogue/category/books/childrens_11/index.html')

In [11]:
def scrape_category(category_name, category_url):

    books = []
    url = category_url

    while url:

        soup = get_soup(url)

        book_cards = soup.select("article.product_pod")

        for book in book_cards:

            title = book.select_one("h3 a")["title"].strip()

            price = book.select_one(
                ".price_color"
            ).get_text(strip=True)

            price_gbp = clean_price(price)

            rating_class = book.select_one(
                "p.star-rating"
            )["class"]

            rating_word = [
                x for x in rating_class
                if x != "star-rating"
            ][0]

            rating = rating_to_int(rating_word)

            availability = book.select_one(
                ".availability"
            ).get_text(" ", strip=True)

            in_stock = "In stock" in availability

            books.append({
                "title": title,
                "category": category_name,
                "price_gbp": price_gbp,
                "rating": rating,
                "in_stock": in_stock
            })

        next_link = soup.select_one("li.next a")

        if next_link:
            url = requests.compat.urljoin(
                url,
                next_link["href"]
            )
            time.sleep(0.1)
        else:
            url = None

    return books

In [12]:
all_books = []

selected_categories = categories[:6]

print("Categories selected:")
for name, url in selected_categories:
    print("-", name)

for category_name, category_url in selected_categories:

    print("\nScraping:", category_name)

    category_books = scrape_category(
        category_name,
        category_url
    )

    print("Books found:", len(category_books))

    all_books.extend(category_books)

print("\nTotal books scraped:", len(all_books))

Categories selected:
- Travel
- Mystery
- Historical Fiction
- Sequential Art
- Classics
- Philosophy

Scraping: Travel
Books found: 11

Scraping: Mystery
Books found: 32

Scraping: Historical Fiction
Books found: 26

Scraping: Sequential Art
Books found: 75

Scraping: Classics
Books found: 19

Scraping: Philosophy
Books found: 11

Total books scraped: 174

In [13]:
df = pd.DataFrame(all_books)

print("Shape:", df.shape)

display(df.head(10))

Shape: (174, 5)

,title,category,price_gbp,rating,in_stock
0,It's Only the Himalayas,Travel,45.17,2,True
1,Full Moon over Noahâs Ark: An Odyssey to Mou...,Travel,49.43,4,True
2,See America: A Celebration of Our National Par...,Travel,48.87,3,True
3,Vagabonding: An Uncommon Guide to the Art of L...,Travel,36.94,2,True
4,Under the Tuscan Sun,Travel,37.33,3,True
5,A Summer In Europe,Travel,44.34,2,True
6,The Great Railway Bazaar,Travel,30.54,1,True
7,A Year in Provence (Provence #1),Travel,56.88,4,True
8,The Road to Little Dribbling: Adventures of an...,Travel,23.21,1,True
9,Neither Here nor There: Travels in Europe,Travel,38.95,3,True

In [14]:
print("Number of books:", len(df))

print(
    "Number of categories:",
    df["category"].nunique()
)

print("\nBooks per category:")

display(
    df.groupby("category")
      .size()
      .reset_index(name="book_count")
)

Number of books: 174
Number of categories: 6

Books per category:

             category  book_count
0            Classics          19
1  Historical Fiction          26
2             Mystery          32
3          Philosophy          11
4      Sequential Art          75
5              Travel          11

In [15]:
# Remove duplicate books
df = df.drop_duplicates(
    subset=["title", "category"]
).copy()

# Clean text columns
df["title"] = df["title"].astype("string").str.strip()
df["category"] = df["category"].astype("string").str.strip()

# Convert price to numeric
df["price_gbp"] = pd.to_numeric(
    df["price_gbp"],
    errors="coerce"
)

# Convert rating to integer
df["rating"] = pd.to_numeric(
    df["rating"],
    errors="coerce"
).astype("Int64")

# Convert stock status to Boolean
df["in_stock"] = df["in_stock"].astype(bool)

# Remove invalid rows
df = df.dropna(
    subset=[
        "title",
        "category",
        "price_gbp",
        "rating"
    ]
)

# Keep rating between 1 and 5
df = df[
    df["rating"].between(1, 5)
]

# Keep non-negative prices
df = df[
    df["price_gbp"] >= 0
]

# Convert rating to normal int
df["rating"] = df["rating"].astype(int)

# Calculate INR price
df["price_inr"] = (
    df["price_gbp"] * GBP_TO_INR
).round(2)

# Ensure numeric types
df["price_gbp"] = df["price_gbp"].astype(float)
df["price_inr"] = df["price_inr"].astype(float)
df["in_stock"] = df["in_stock"].astype(bool)

df = df.reset_index(drop=True)

print("Cleaning completed.")
print("Rows:", len(df))

Cleaning completed.
Rows: 174

In [16]:
print("========== ACCEPTANCE CHECKS ==========")

print(
    "Books >= 60:",
    len(df) >= 60,
    "| Count =", len(df)
)

print(
    "Categories >= 3:",
    df["category"].nunique() >= 3,
    "| Count =", df["category"].nunique()
)

print(
    "price_gbp exists:",
    "price_gbp" in df.columns
)

print(
    "rating exists:",
    "rating" in df.columns
)

print(
    "in_stock exists:",
    "in_stock" in df.columns
)

print(
    "price_inr exists:",
    "price_inr" in df.columns
)

print(
    "Rating valid:",
    df["rating"].between(1, 5).all()
)

print(
    "Fixed rate:",
    GBP_TO_INR,
)

print("\n========== DATA TYPES ==========")

print(df.dtypes)

========== ACCEPTANCE CHECKS ==========
Books >= 60: True | Count = 174
Categories >= 3: True | Count = 6
price_gbp exists: True
rating exists: True
in_stock exists: True
price_inr exists: True
Rating valid: True
Fixed rate: 105.5

========== DATA TYPES ==========
title        string[python]
category     string[python]
price_gbp           float64
rating                int64
in_stock               bool
price_inr           float64
dtype: object

In [17]:
display(df.head(20))

,title,category,price_gbp,rating,in_stock,price_inr
0,It's Only the Himalayas,Travel,45.17,2,True,4765.44
1,Full Moon over Noahâs Ark: An Odyssey to Mou...,Travel,49.43,4,True,5214.86
2,See America: A Celebration of Our National Par...,Travel,48.87,3,True,5155.78
3,Vagabonding: An Uncommon Guide to the Art of L...,Travel,36.94,2,True,3897.17
4,Under the Tuscan Sun,Travel,37.33,3,True,3938.31
5,A Summer In Europe,Travel,44.34,2,True,4677.87
6,The Great Railway Bazaar,Travel,30.54,1,True,3221.97
7,A Year in Provence (Provence #1),Travel,56.88,4,True,6000.84
8,The Road to Little Dribbling: Adventures of an...,Travel,23.21,1,True,2448.66
9,Neither Here nor There: Travels in Europe,Travel,38.95,3,True,4109.23
10,"1,000 Places to See Before You Die",Travel,26.08,5,True,2751.44
11,Sharp Objects,Mystery,47.82,4,True,5045.01
12,"In a Dark, Dark Wood",Mystery,19.63,1,True,2070.96
13,The Past Never Ends,Mystery,56.50,4,True,5960.75
14,A Murder in Time,Mystery,16.64,1,True,1755.52
15,The Murder of Roger Ackroyd (Hercule Poirot #4),Mystery,44.10,4,True,4652.55
16,The Last Mile (Amos Decker #2),Mystery,54.21,2,True,5719.16
17,That Darkness (Gardiner and Renner #1),Mystery,13.92,1,True,1468.56
18,Tastes Like Fear (DI Marnie Rome #3),Mystery,10.69,1,True,1127.79
19,A Time of Torment (Charlie Parker #14),Mystery,48.35,5,True,5100.92

In [18]:
df.to_csv(
    "books_cleaned.csv",
    index=False
)

print("books_cleaned.csv created.")

books_cleaned.csv created.

In [19]:
DB_PATH = "books.db"

conn = sqlite3.connect(DB_PATH)

# Enable foreign keys
conn.execute("PRAGMA foreign_keys = ON")

# Remove old tables if they exist
conn.executescript("""
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS categories;
""")

# Create categories table
conn.execute("""
CREATE TABLE categories (
    category_id INTEGER PRIMARY KEY AUTOINCREMENT,
    category_name TEXT NOT NULL UNIQUE
);
""")

# Create books table
conn.execute("""
CREATE TABLE books (
    book_id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    category_id INTEGER NOT NULL,
    price_gbp REAL NOT NULL,
    rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),
    in_stock INTEGER NOT NULL CHECK(in_stock IN (0,1)),
    price_inr REAL NOT NULL,

    FOREIGN KEY(category_id)
        REFERENCES categories(category_id)
);
""")

conn.commit()

print("SQLite database created.")

SQLite database created.

In [20]:
unique_categories = sorted(
    df["category"].unique()
)

for category in unique_categories:

    conn.execute(
        """
        INSERT INTO categories(category_name)
        VALUES (?)
        """,
        (category,)
    )

conn.commit()

categories_df = pd.read_sql(
    "SELECT * FROM categories",
    conn
)

display(categories_df)

   category_id       category_name
0            1            Classics
1            2  Historical Fiction
2            3             Mystery
3            4          Philosophy
4            5      Sequential Art
5            6              Travel

In [21]:
category_map = dict(
    conn.execute(
        """
        SELECT category_name, category_id
        FROM categories
        """
    ).fetchall()
)

records = []

for row in df.itertuples(index=False):

    records.append(
        (
            row.title,
            category_map[row.category],
            float(row.price_gbp),
            int(row.rating),
            int(row.in_stock),
            float(row.price_inr)
        )
    )

conn.executemany(
    """
    INSERT INTO books
    (
        title,
        category_id,
        price_gbp,
        rating,
        in_stock,
        price_inr
    )
    VALUES (?, ?, ?, ?, ?, ?)
    """,
    records
)

conn.commit()

print("Inserted", len(records), "books.")

Inserted 174 books.

In [22]:
tables = pd.read_sql(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    """,
    conn
)

display(tables)

              name
0       categories
1  sqlite_sequence
2            books

In [23]:
books_db = pd.read_sql(
    "SELECT * FROM books LIMIT 10",
    conn
)

display(books_db)

,book_id,title,category_id,price_gbp,rating,in_stock,price_inr
0,1,It's Only the Himalayas,6,45.17,2,1,4765.44
1,2,Full Moon over Noahâs Ark: An Odyssey to Mou...,6,49.43,4,1,5214.86
2,3,See America: A Celebration of Our National Par...,6,48.87,3,1,5155.78
3,4,Vagabonding: An Uncommon Guide to the Art of L...,6,36.94,2,1,3897.17
4,5,Under the Tuscan Sun,6,37.33,3,1,3938.31
5,6,A Summer In Europe,6,44.34,2,1,4677.87
6,7,The Great Railway Bazaar,6,30.54,1,1,3221.97
7,8,A Year in Provence (Provence #1),6,56.88,4,1,6000.84
8,9,The Road to Little Dribbling: Adventures of an...,6,23.21,1,1,2448.66
9,10,Neither Here nor There: Travels in Europe,6,38.95,3,1,4109.23

In [24]:
print("Categories table:")
display(
    pd.read_sql(
        "PRAGMA table_info(categories)",
        conn
    )
)

print("\nBooks table:")
display(
    pd.read_sql(
        "PRAGMA table_info(books)",
        conn
    )
)

print("\nForeign Keys:")
display(
    pd.read_sql(
        "PRAGMA foreign_key_list(books)",
        conn
    )
)

Categories table:

   cid           name     type  notnull dflt_value  pk
0    0    category_id  INTEGER        0       None   1
1    1  category_name     TEXT        1       None   0

Books table:

   cid         name     type  notnull dflt_value  pk
0    0      book_id  INTEGER        0       None   1
1    1        title     TEXT        1       None   0
2    2  category_id  INTEGER        1       None   0
3    3    price_gbp     REAL        1       None   0
4    4       rating  INTEGER        1       None   0
5    5     in_stock  INTEGER        1       None   0
6    6    price_inr     REAL        1       None   0

Foreign Keys:

   id  seq       table         from           to  on_update  on_delete match
0   0    0  categories  category_id  category_id  NO ACTION  NO ACTION  NONE

In [25]:
query1 = """
SELECT
    title,
    price_gbp,
    rating
FROM books
WHERE price_gbp < 20
AND rating >= 4
ORDER BY price_gbp ASC
LIMIT 10;
"""

result1 = pd.read_sql(query1, conn)

display(result1)

                                               title  price_gbp  rating
0           Fruits Basket, Vol. 2 (Fruits Basket #2)      11.64       5
1  Superman Vol. 1: Before Truth (Superman by Gen...      11.89       5
2                                  The Girl You Lost      12.29       5
3  Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...      13.61       5
4                                        Roller Girl      14.10       5
5                                  The Secret Garden      15.08       4
6           Batman: The Dark Knight Returns (Batman)      15.38       5
7  Outcast, Vol. 1: A Darkness Surrounds Him (Out...      15.44       4
8                                     Sophie's World      15.94       5
9  A Spy's Devotion (The Regency Spies of London #1)      16.97       5

In [26]:
query2 = """
SELECT DISTINCT
    c.category_name
FROM categories c
WHERE c.category_name LIKE '%Fiction%';
"""

result2 = pd.read_sql(query2, conn)

display(result2)

        category_name
0  Historical Fiction

In [27]:
query3 = """
SELECT
    title,
    price_gbp,
    rating
FROM books
WHERE price_gbp BETWEEN 10 AND 30
AND rating IN (4, 5)
ORDER BY rating DESC, price_gbp ASC;
"""

result3 = pd.read_sql(query3, conn)

display(result3)

                                                title  price_gbp  rating
0            Fruits Basket, Vol. 2 (Fruits Basket #2)      11.64       5
1   Superman Vol. 1: Before Truth (Superman by Gen...      11.89       5
2                                   The Girl You Lost      12.29       5
3   Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...      13.61       5
4                                         Roller Girl      14.10       5
5            Batman: The Dark Knight Returns (Batman)      15.38       5
6                                      Sophie's World      15.94       5
7   A Spy's Devotion (The Regency Spies of London #1)      16.97       5
8                              Between Shades of Gray      20.79       5
9                              Voyager (Outlander #3)      21.07       5
10      Saga, Volume 3 (Saga (Collected Editions) #3)      21.57       5
11                  The Silkworm (Cormoran Strike #2)      23.05       5
12  What Happened on Beale Street (Secrets of the ...      25.37       5
13                 1,000 Places to See Before You Die      26.08       5
14                              The Passion of Dolssa      28.32       5
15  At The Existentialist CafÃ©: Freedom, Being, a...      29.93       5
16                                  The Secret Garden      15.08       4
17  Outcast, Vol. 1: A Darkness Surrounds Him (Out...      15.44       4
18                                      Camp Midnight      17.08       4
19                                       The Stranger      17.44       4
20  Y: The Last Man, Vol. 1: Unmanned (Y: The Last...      18.51       4
21                                    This One Summer      19.49       4
22   Delivering the Truth (Quaker Midwife Mystery #1)      20.89       4
23           Fruits Basket, Vol. 6 (Fruits Basket #6)      20.96       4
24             Paper Girls, Vol. 1 (Paper Girls #1-5)      21.71       4
25  The Mysterious Affair at Styles (Hercule Poiro...      24.80       4
26  The Complete Stories and Poems (The Works of E...      26.78       4
27                              Lost Among the Living      27.70       4
28                     Little Women (Little Women #1)      28.07       4
29                          The Marriage of Opposites      28.08       4

In [28]:
query4 = """
SELECT
    c.category_name,
    COUNT(b.book_id) AS book_count,
    ROUND(AVG(b.price_gbp), 2) AS average_price_gbp
FROM categories c
JOIN books b
ON c.category_id = b.category_id
GROUP BY c.category_name
ORDER BY book_count DESC;
"""

result4 = pd.read_sql(query4, conn)

display(result4)

        category_name  book_count  average_price_gbp
0      Sequential Art          75              34.57
1             Mystery          32              31.72
2  Historical Fiction          26              33.64
3            Classics          19              36.55
4              Travel          11              39.79
5          Philosophy          11              33.56

In [29]:
query5 = """
SELECT
    c.category_name,
    COUNT(b.book_id) AS book_count
FROM categories c
JOIN books b
ON c.category_id = b.category_id
GROUP BY c.category_name
HAVING COUNT(b.book_id) >= 5
ORDER BY book_count DESC;
"""

result5 = pd.read_sql(query5, conn)

display(result5)

        category_name  book_count
0      Sequential Art          75
1             Mystery          32
2  Historical Fiction          26
3            Classics          19
4              Travel          11
5          Philosophy          11

In [30]:
query6 = """
SELECT
    b.book_id,
    b.title,
    c.category_name,
    b.price_gbp,
    b.rating,
    b.in_stock,
    b.price_inr
FROM books b
JOIN categories c
ON b.category_id = c.category_id
ORDER BY c.category_name, b.title
LIMIT 20;
"""

result6 = pd.read_sql(query6, conn)

display(result6)

,book_id,title,category_name,price_gbp,rating,in_stock,price_inr
0,163,Alice in Wonderland (Alice's Adventures in Won...,Classics,55.53,1,1,5858.42
1,157,And Then There Were None,Classics,35.01,2,1,3693.56
2,152,Animal Farm,Classics,57.22,3,1,6036.71
3,156,Beowulf,Classics,38.35,2,1,4045.92
4,151,Candide,Classics,58.63,3,1,6185.46
5,162,Emma,Classics,32.93,2,1,3474.12
6,150,Gone with the Wind,Classics,32.49,3,1,3427.70
7,149,Little Women (Little Women #1),Classics,28.07,4,1,2961.38
8,161,Of Mice and Men,Classics,47.11,2,1,4970.10
9,160,Sense and Sensibility,Classics,37.46,1,1,3952.03
10,155,The Complete Stories and Poems (The Works of E...,Classics,26.78,4,1,2825.29
11,148,The Hound of the Baskervilles (Sherlock Holmes...,Classics,14.82,2,1,1563.51
12,159,The Little Prince,Classics,45.42,2,1,4791.81
13,146,The Metamorphosis,Classics,28.58,1,1,3015.19
14,154,The Picture of Dorian Gray,Classics,29.70,2,1,3133.35
15,147,The Pilgrim's Progress,Classics,50.26,2,1,5302.43
16,145,The Secret Garden,Classics,15.08,4,1,1590.94
17,158,The Story of Hong Gildong,Classics,43.19,4,1,4556.54
18,153,Wuthering Heights,Classics,17.73,3,1,1870.52
19,46,A Flight of Arrows (The Pathfinders #2),Historical Fiction,55.53,5,1,5858.42

In [31]:
query7 = """
SELECT
    COUNT(*) AS total_books,
    ROUND(MIN(price_gbp), 2) AS minimum_price_gbp,
    ROUND(MAX(price_gbp), 2) AS maximum_price_gbp,
    ROUND(AVG(price_gbp), 2) AS average_price_gbp,
    SUM(
        CASE
            WHEN in_stock = 1 THEN 1
            ELSE 0
        END
    ) AS books_in_stock
FROM books;
"""

result7 = pd.read_sql(query7, conn)

display(result7)

,total_books,minimum_price_gbp,maximum_price_gbp,average_price_gbp,books_in_stock
0,174,10.16,59.48,34.39,174

In [32]:
query8 = """
SELECT
    title,
    rating,

    CASE
        WHEN rating = 5 THEN 'Excellent'
        WHEN rating = 4 THEN 'Very Good'
        WHEN rating = 3 THEN 'Good'
        ELSE 'Below Average'
    END AS rating_label

FROM books
ORDER BY rating DESC, title
LIMIT 15;
"""

result8 = pd.read_sql(query8, conn)

display(result8)

                                                title  rating rating_label
0                  1,000 Places to See Before You Die       5    Excellent
1             A Flight of Arrows (The Pathfinders #2)       5    Excellent
2   A Spy's Devotion (The Regency Spies of London #1)       5    Excellent
3              A Time of Torment (Charlie Parker #14)       5    Excellent
4   At The Existentialist CafÃ©: Freedom, Being, a...       5    Excellent
5            Batman: The Dark Knight Returns (Batman)       5    Excellent
6                              Between Shades of Gray       5    Excellent
7   Bleach, Vol. 1: Strawberry and the Soul Reaper...       5    Excellent
8                                            El Deafo       5    Excellent
9            Fruits Basket, Vol. 1 (Fruits Basket #1)       5    Excellent
10           Fruits Basket, Vol. 2 (Fruits Basket #2)       5    Excellent
11                                       Mrs. Houdini       5    Excellent
12  Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...       5    Excellent
13  Rat Queens, Vol. 1: Sass & Sorcery (Rat Queens...       5    Excellent
14                                        Roller Girl       5    Excellent

In [33]:
queries = {
    "Q1 SELECT WHERE AND ORDER BY LIMIT": query1,
    "Q2 DISTINCT LIKE": query2,
    "Q3 BETWEEN IN": query3,
    "Q4 JOIN GROUP BY": query4,
    "Q5 HAVING": query5,
    "Q6 JOIN": query6,
    "Q7 AGGREGATES": query7,
    "Q8 CASE": query8
}

with open(
    "sql_output.txt",
    "w",
    encoding="utf-8"
) as file:

    for name, query in queries.items():

        result = pd.read_sql(
            query,
            conn
        )

        file.write(
            "\n" + "=" * 80 + "\n"
        )

        file.write(
            name + "\n"
        )

        file.write(
            "=" * 80 + "\n"
        )

        file.write(
            result.to_string(index=False)
        )

        file.write("\n")

print("sql_output.txt created.")

sql_output.txt created.

In [34]:
sql_join = """
SELECT
    b.book_id,
    b.title,
    b.category_id,
    c.category_name,
    b.price_gbp,
    b.rating,
    b.in_stock,
    b.price_inr

FROM books b

JOIN categories c
ON b.category_id = c.category_id

ORDER BY b.book_id;
"""

sql_df = pd.read_sql(
    sql_join,
    conn
)

display(sql_df.head(20))

,book_id,title,category_id,category_name,price_gbp,rating,in_stock,price_inr
0,1,It's Only the Himalayas,6,Travel,45.17,2,1,4765.44
1,2,Full Moon over Noahâs Ark: An Odyssey to Mou...,6,Travel,49.43,4,1,5214.86
2,3,See America: A Celebration of Our National Par...,6,Travel,48.87,3,1,5155.78
3,4,Vagabonding: An Uncommon Guide to the Art of L...,6,Travel,36.94,2,1,3897.17
4,5,Under the Tuscan Sun,6,Travel,37.33,3,1,3938.31
5,6,A Summer In Europe,6,Travel,44.34,2,1,4677.87
6,7,The Great Railway Bazaar,6,Travel,30.54,1,1,3221.97
7,8,A Year in Provence (Provence #1),6,Travel,56.88,4,1,6000.84
8,9,The Road to Little Dribbling: Adventures of an...,6,Travel,23.21,1,1,2448.66
9,10,Neither Here nor There: Travels in Europe,6,Travel,38.95,3,1,4109.23
10,11,"1,000 Places to See Before You Die",6,Travel,26.08,5,1,2751.44
11,12,Sharp Objects,3,Mystery,47.82,4,1,5045.01
12,13,"In a Dark, Dark Wood",3,Mystery,19.63,1,1,2070.96
13,14,The Past Never Ends,3,Mystery,56.50,4,1,5960.75
14,15,A Murder in Time,3,Mystery,16.64,1,1,1755.52
15,16,The Murder of Roger Ackroyd (Hercule Poirot #4),3,Mystery,44.10,4,1,4652.55
16,17,The Last Mile (Amos Decker #2),3,Mystery,54.21,2,1,5719.16
17,18,That Darkness (Gardiner and Renner #1),3,Mystery,13.92,1,1,1468.56
18,19,Tastes Like Fear (DI Marnie Rome #3),3,Mystery,10.69,1,1,1127.79
19,20,A Time of Torment (Charlie Parker #14),3,Mystery,48.35,5,1,5100.92

In [35]:
books_df = pd.read_sql(
    """
    SELECT *
    FROM books
    ORDER BY book_id
    """,
    conn
)

categories_df = pd.read_sql(
    """
    SELECT *
    FROM categories
    ORDER BY category_id
    """,
    conn
)

merge_df = pd.merge(
    books_df,
    categories_df,
    on="category_id",
    how="inner"
)

merge_df = merge_df[
    [
        "book_id",
        "title",
        "category_id",
        "category_name",
        "price_gbp",
        "rating",
        "in_stock",
        "price_inr"
    ]
]

merge_df = merge_df.sort_values(
    "book_id"
).reset_index(drop=True)

display(merge_df.head(20))

,book_id,title,category_id,category_name,price_gbp,rating,in_stock,price_inr
0,1,It's Only the Himalayas,6,Travel,45.17,2,1,4765.44
1,2,Full Moon over Noahâs Ark: An Odyssey to Mou...,6,Travel,49.43,4,1,5214.86
2,3,See America: A Celebration of Our National Par...,6,Travel,48.87,3,1,5155.78
3,4,Vagabonding: An Uncommon Guide to the Art of L...,6,Travel,36.94,2,1,3897.17
4,5,Under the Tuscan Sun,6,Travel,37.33,3,1,3938.31
5,6,A Summer In Europe,6,Travel,44.34,2,1,4677.87
6,7,The Great Railway Bazaar,6,Travel,30.54,1,1,3221.97
7,8,A Year in Provence (Provence #1),6,Travel,56.88,4,1,6000.84
8,9,The Road to Little Dribbling: Adventures of an...,6,Travel,23.21,1,1,2448.66
9,10,Neither Here nor There: Travels in Europe,6,Travel,38.95,3,1,4109.23
10,11,"1,000 Places to See Before You Die",6,Travel,26.08,5,1,2751.44
11,12,Sharp Objects,3,Mystery,47.82,4,1,5045.01
12,13,"In a Dark, Dark Wood",3,Mystery,19.63,1,1,2070.96
13,14,The Past Never Ends,3,Mystery,56.50,4,1,5960.75
14,15,A Murder in Time,3,Mystery,16.64,1,1,1755.52
15,16,The Murder of Roger Ackroyd (Hercule Poirot #4),3,Mystery,44.10,4,1,4652.55
16,17,The Last Mile (Amos Decker #2),3,Mystery,54.21,2,1,5719.16
17,18,That Darkness (Gardiner and Renner #1),3,Mystery,13.92,1,1,1468.56
18,19,Tastes Like Fear (DI Marnie Rome #3),3,Mystery,10.69,1,1,1127.79
19,20,A Time of Torment (Charlie Parker #14),3,Mystery,48.35,5,1,5100.92

In [36]:
sql_first20 = sql_df.head(20).reset_index(drop=True)
merge_first20 = merge_df.head(20).reset_index(drop=True)

side_by_side = pd.concat(
    [
        sql_first20.add_prefix("SQL_"),
        merge_first20.add_prefix("PANDAS_")
    ],
    axis=1
)

display(side_by_side)

,SQL_book_id,SQL_title,SQL_category_id,SQL_category_name,SQL_price_gbp,SQL_rating,SQL_in_stock,SQL_price_inr,PANDAS_book_id,PANDAS_title,PANDAS_category_id,PANDAS_category_name,PANDAS_price_gbp,PANDAS_rating,PANDAS_in_stock,PANDAS_price_inr
0,1,It's Only the Himalayas,6,Travel,45.17,2,1,4765.44,1,It's Only the Himalayas,6,Travel,45.17,2,1,4765.44
1,2,Full Moon over Noahâs Ark: An Odyssey to Mou...,6,Travel,49.43,4,1,5214.86,2,Full Moon over Noahâs Ark: An Odyssey to Mou...,6,Travel,49.43,4,1,5214.86
2,3,See America: A Celebration of Our National Par...,6,Travel,48.87,3,1,5155.78,3,See America: A Celebration of Our National Par...,6,Travel,48.87,3,1,5155.78
3,4,Vagabonding: An Uncommon Guide to the Art of L...,6,Travel,36.94,2,1,3897.17,4,Vagabonding: An Uncommon Guide to the Art of L...,6,Travel,36.94,2,1,3897.17
4,5,Under the Tuscan Sun,6,Travel,37.33,3,1,3938.31,5,Under the Tuscan Sun,6,Travel,37.33,3,1,3938.31
5,6,A Summer In Europe,6,Travel,44.34,2,1,4677.87,6,A Summer In Europe,6,Travel,44.34,2,1,4677.87
6,7,The Great Railway Bazaar,6,Travel,30.54,1,1,3221.97,7,The Great Railway Bazaar,6,Travel,30.54,1,1,3221.97
7,8,A Year in Provence (Provence #1),6,Travel,56.88,4,1,6000.84,8,A Year in Provence (Provence #1),6,Travel,56.88,4,1,6000.84
8,9,The Road to Little Dribbling: Adventures of an...,6,Travel,23.21,1,1,2448.66,9,The Road to Little Dribbling: Adventures of an...,6,Travel,23.21,1,1,2448.66
9,10,Neither Here nor There: Travels in Europe,6,Travel,38.95,3,1,4109.23,10,Neither Here nor There: Travels in Europe,6,Travel,38.95,3,1,4109.23
10,11,"1,000 Places to See Before You Die",6,Travel,26.08,5,1,2751.44,11,"1,000 Places to See Before You Die",6,Travel,26.08,5,1,2751.44
11,12,Sharp Objects,3,Mystery,47.82,4,1,5045.01,12,Sharp Objects,3,Mystery,47.82,4,1,5045.01
12,13,"In a Dark, Dark Wood",3,Mystery,19.63,1,1,2070.96,13,"In a Dark, Dark Wood",3,Mystery,19.63,1,1,2070.96
13,14,The Past Never Ends,3,Mystery,56.50,4,1,5960.75,14,The Past Never Ends,3,Mystery,56.50,4,1,5960.75
14,15,A Murder in Time,3,Mystery,16.64,1,1,1755.52,15,A Murder in Time,3,Mystery,16.64,1,1,1755.52
15,16,The Murder of Roger Ackroyd (Hercule Poirot #4),3,Mystery,44.10,4,1,4652.55,16,The Murder of Roger Ackroyd (Hercule Poirot #4),3,Mystery,44.10,4,1,4652.55
16,17,The Last Mile (Amos Decker #2),3,Mystery,54.21,2,1,5719.16,17,The Last Mile (Amos Decker #2),3,Mystery,54.21,2,1,5719.16
17,18,That Darkness (Gardiner and Renner #1),3,Mystery,13.92,1,1,1468.56,18,That Darkness (Gardiner and Renner #1),3,Mystery,13.92,1,1,1468.56
18,19,Tastes Like Fear (DI Marnie Rome #3),3,Mystery,10.69,1,1,1127.79,19,Tastes Like Fear (DI Marnie Rome #3),3,Mystery,10.69,1,1,1127.79
19,20,A Time of Torment (Charlie Parker #14),3,Mystery,48.35,5,1,5100.92,20,A Time of Torment (Charlie Parker #14),3,Mystery,48.35,5,1,5100.92

In [37]:
same_shape = sql_df.shape == merge_df.shape
same_values = sql_df.equals(merge_df)

print("SQL DataFrame shape:", sql_df.shape)
print("Pandas DataFrame shape:", merge_df.shape)

print("\nSame shape:", same_shape)
print("Same values:", same_values)

if same_shape and same_values:
    print(
        "\nSUCCESS: pd.read_sql JOIN and pd.merge outputs MATCH."
    )
else:
    print(
        "\nERROR: Outputs do not match."
    )

SQL DataFrame shape: (174, 8)
Pandas DataFrame shape: (174, 8)

Same shape: True
Same values: True

SUCCESS: pd.read_sql JOIN and pd.merge outputs MATCH.

In [38]:
with open(
    "join_comparison.txt",
    "w",
    encoding="utf-8"
) as file:

    file.write(
        "=== pd.read_sql JOIN OUTPUT ===\n\n"
    )

    file.write(
        sql_df.head(20).to_string(index=False)
    )

    file.write(
        "\n\n=== pd.merge OUTPUT ===\n\n"
    )

    file.write(
        merge_df.head(20).to_string(index=False)
    )

    file.write(
        "\n\n=== SIDE BY SIDE ===\n\n"
    )

    file.write(
        side_by_side.to_string(index=False)
    )

    file.write(
        f"\n\nSame shape: {same_shape}"
    )

    file.write(
        f"\nSame values: {same_values}"
    )

print("join_comparison.txt created.")

join_comparison.txt created.

In [39]:
print("=" * 60)
print("FINAL PROJECT ACCEPTANCE TEST")
print("=" * 60)

checks = {
    "At least 60 books":
        len(df) >= 60,

    "At least 3 categories":
        df["category"].nunique() >= 3,

    "price_gbp exists":
        "price_gbp" in df.columns,

    "rating exists":
        "rating" in df.columns,

    "in_stock exists":
        "in_stock" in df.columns,

    "price_inr exists":
        "price_inr" in df.columns,

    "Rating 1-5":
        df["rating"].between(1, 5).all(),

    "price_gbp is float":
        pd.api.types.is_float_dtype(df["price_gbp"]),

    "rating is integer":
        pd.api.types.is_integer_dtype(df["rating"]),

    "in_stock is bool":
        pd.api.types.is_bool_dtype(df["in_stock"]),

    "price_inr is float":
        pd.api.types.is_float_dtype(df["price_inr"]),

    "SQL/Pandas JOIN matches":
        sql_df.equals(merge_df),

    "SQLite database exists":
        Path("books.db").exists(),

    "SQL output exists":
        Path("sql_output.txt").exists()
}

for check, passed in checks.items():
    print(
        f"{'PASS' if passed else 'FAIL'} : {check}"
    )

print("=" * 60)

if all(checks.values()):
    print("🎉 ALL ACCEPTANCE CRITERIA PASSED!")
else:
    print("⚠️ Some acceptance criteria failed.")

============================================================
FINAL PROJECT ACCEPTANCE TEST
============================================================
PASS : At least 60 books
PASS : At least 3 categories
PASS : price_gbp exists
PASS : rating exists
PASS : in_stock exists
PASS : price_inr exists
PASS : Rating 1-5
PASS : price_gbp is float
PASS : rating is integer
PASS : in_stock is bool
PASS : price_inr is float
PASS : SQL/Pandas JOIN matches
PASS : SQLite database exists
PASS : SQL output exists
============================================================
🎉 ALL ACCEPTANCE CRITERIA PASSED!

In [40]:
readme = """
# Data Pipeline Project

## Overview

This project automatically scrapes book data from Books to Scrape,
cleans the data using pandas, calculates INR prices, stores the data
in SQLite, and performs SQL analysis.

## Fixed GBP to INR Rate

1 GBP = 105.50 INR

This is a fixed project-defined conversion rate and is not based on
a date-specific exchange rate.

## Dataset

The pipeline automatically collects at least 60 books from at least
3 categories.

## Columns

- title
- category
- price_gbp
- rating
- in_stock
- price_inr

## Cleaning Decisions

1. Removed the pound symbol from prices.
2. Converted prices to float.
3. Converted ratings One-Five to integers 1-5.
4. Converted stock status to Boolean.
5. Removed duplicate title/category combinations.
6. Removed invalid or missing prices and ratings.
7. Calculated price_inr using 105.50.

## Database

Two tables are used:

categories:
- category_id PRIMARY KEY
- category_name

books:
- book_id PRIMARY KEY
- title
- category_id FOREIGN KEY
- price_gbp
- rating
- in_stock
- price_inr

## SQL

The notebook demonstrates:

SELECT, WHERE, AND, DISTINCT, LIKE, BETWEEN, IN,
ORDER BY, LIMIT, GROUP BY, HAVING, JOIN,
aggregate functions and CASE.

## Pandas JOIN

The same join is performed using:

pd.read_sql()

and

pd.merge()

The notebook verifies that both outputs match.

## Files Generated

- books_cleaned.csv
- books.db
- sql_output.txt
- join_comparison.txt
"""

with open(
    "README.md",
    "w",
    encoding="utf-8"
) as file:
    file.write(readme)

print("README.md created.")

README.md created.

In [41]:
import zipfile
from pathlib import Path

files_to_zip = [
    "books_cleaned.csv",
    "books.db",
    "sql_output.txt",
    "join_comparison.txt",
    "README.md"
]

zip_name = "data_pipeline_submission.zip"

with zipfile.ZipFile(
    zip_name,
    "w",
    zipfile.ZIP_DEFLATED
) as zip_file:

    for file_name in files_to_zip:

        if Path(file_name).exists():

            zip_file.write(
                file_name
            )

print("Created:", zip_name)

Created: data_pipeline_submission.zip

In [42]:
from google.colab import files

files.download(
    "data_pipeline_submission.zip"
)

In [65]:
%cd /content

print("Folders:")
!find /content -maxdepth 3 -type f | head -100

/content
Folders:
/content/.config/.last_opt_in_prompt.yaml
/content/.config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db
/content/.config/configurations/config_default
/content/.config/active_config
/content/.config/.last_survey_prompt.yaml
/content/.config/config_sentinel
/content/.config/.last_update_check.json
/content/.config/default_configs.db
/content/.config/gce
/content/books_cleaned.csv
/content/books.db
/content/capstone_project/.git/description
/content/capstone_project/.git/COMMIT_EDITMSG
/content/capstone_project/.git/HEAD
/content/capstone_project/.git/index
/content/capstone_project/.git/config
/content/sql_output.txt
/content/join_comparison.txt
/content/data_pipeline_submission.zip
/content/README.md
/content/sample_data/anscombe.json
/content/sample_data/README.md
/content/sample_data/california_housing_test.csv
/content/sample_data/mnist_train_small.csv
/content/sample_data/california_housing_train.csv
/content/sample_data/mnist_test.csv

In [66]:
# Go to your Git repository
%cd /content/capstone_project

# Create the required data_pipeline folder
!mkdir -p data_pipeline

# Copy your project files into data_pipeline
!cp /content/books_cleaned.csv data_pipeline/
!cp /content/books.db data_pipeline/
!cp /content/sql_output.txt data_pipeline/
!cp /content/join_comparison.txt data_pipeline/
!cp /content/README.md data_pipeline/

# Check the files
!find data_pipeline -maxdepth 1 -type f -print

/content/capstone_project
data_pipeline/books_cleaned.csv
data_pipeline/books.db
data_pipeline/sql_output.txt
data_pipeline/join_comparison.txt
data_pipeline/README.md

In [67]:
%cd /content/capstone_project

!git add .
!git status

/content/capstone_project
On branch main

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   data_pipeline/README.md
	new file:   data_pipeline/books.db
	new file:   data_pipeline/books_cleaned.csv
	new file:   data_pipeline/join_comparison.txt
	new file:   data_pipeline/sql_output.txt

In [68]:
!git commit -m "Initial data pipeline project"
!git branch -M main
!git push -u origin main

[main (root-commit) 997d1b2] Initial data pipeline project
 5 files changed, 461 insertions(+)
 create mode 100644 data_pipeline/README.md
 create mode 100644 data_pipeline/books.db
 create mode 100644 data_pipeline/books_cleaned.csv
 create mode 100644 data_pipeline/join_comparison.txt
 create mode 100644 data_pipeline/sql_output.txt
fatal: could not read Username for 'https://github.com': No such device or address

In [69]:
import getpass

username = "abhuvana17"
token = getpass.getpass("Enter your GitHub Personal Access Token: ")

!git remote set-url origin https://{username}:{token}@github.com/abhuvana17/capstone_project.git

Enter your GitHub Personal Access Token: ··········

In [70]:
!git push -u origin main

Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Delta compression using up to 2 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (8/8), 17.74 KiB | 4.44 MiB/s, done.
Total 8 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/abhuvana17/capstone_project.git
 * [new branch]      main -> main
Branch 'main' set up to track remote branch 'main' from 'origin'.

In [71]:
!git checkout -b feature/data-pipeline
!git add data_pipeline/
!git commit -m "Add scraping and cleaning pipeline"
with open("data_pipeline/README.md", "a") as f:
    f.write("\n\n## Pipeline Status\nScraping, cleaning and validation completed.")
!git add data_pipeline/
!git commit -m "Add SQLite database and SQL analysis"
!git push -u origin feature/data-pipeline
!git checkout main
!git merge feature/data-pipeline
!git push origin main

Switched to a new branch 'feature/data-pipeline'
On branch feature/data-pipeline
nothing to commit, working tree clean
[feature/data-pipeline 491776a] Add SQLite database and SQL analysis
 1 file changed, 4 insertions(+)
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (4/4), 435 bytes | 435.00 KiB/s, done.
Total 4 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote:
remote: Create a pull request for 'feature/data-pipeline' on GitHub by visiting:
remote:      https://github.com/abhuvana17/capstone_project/pull/new/feature/data-pipeline
remote:
To https://github.com/abhuvana17/capstone_project.git
 * [new branch]      feature/data-pipeline -> feature/data-pipeline
Branch 'feature/data-pipeline' set up to track remote branch 'feature/data-pipeline' from 'origin'.
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
Updating 997d1b2..491776a
Fast-forward
 data_pipeline/README.md | 4 ++++
 1 file changed, 4 insertions(+)
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/abhuvana17/capstone_project.git
   997d1b2..491776a  main -> main

In [72]:
%cd /content/capstone_project

!git checkout main
!git add data_pipeline/data_pipeline_project.ipynb
!git commit -m "Add complete data pipeline notebook"
!git push origin main

/content/capstone_project
Already on 'main'
Your branch is up to date with 'origin/main'.
fatal: pathspec 'data_pipeline/data_pipeline_project.ipynb' did not match any files
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
Everything up-to-date

In [73]:
!ls -lh /content/*.ipynb

ls: cannot access '/content/*.ipynb': No such file or directory